// Offline question bank — categorized by topic. Used directly as the "bank"
// source and as the fallback when AI generation is unavailable/fails.
// Shape: { text, topic, answers: [{ text, points }] }  (points sum ~100)
const crypto = require('crypto');
const flagged = require('./flagged');

// ~7,600 real Family Feud questions (ProtoQA dataset, scraped from FF fan sites,
// with crowd-survey counts used as points). Generated by scripts/build-bank.js.
let BANK_QUESTIONS = [];
try { BANK_QUESTIONS = require('./questionBank.json'); } catch { /* bank optional */ }

// Curated Fast Money questions (classic "We asked 100…", scale, "how many…"
// framings) — drawn from for Fast Money on the Bank source.
const FM_CURATED = require('./fastMoneyQuestions');

// Hand-curated questions — kept up front for their tidy topic tags and phrasing.
const CURATED_QUESTIONS = [
  // ---- everyday ----
  {
    text: 'Name something you do first thing in the morning.',
    topic: 'everyday',
    answers: [
      { text: 'Use the bathroom', points: 31 },
      { text: 'Drink coffee', points: 24 },
      { text: 'Check your phone', points: 18 },
      { text: 'Brush your teeth', points: 12 },
      { text: 'Eat breakfast', points: 9 },
      { text: 'Shower', points: 6 },
    ],
  },
  {
    text: 'Name a place where it would be rude to be on your phone.',
    topic: 'everyday',
    answers: [
      { text: 'Church', points: 28 },
      { text: 'A funeral', points: 22 },
      { text: 'A movie theater', points: 19 },
      { text: 'A job interview', points: 16 },
      { text: 'At dinner', points: 9 },
      { text: 'A wedding', points: 6 },
    ],
  },
  {
    text: 'Name something people lose all the time.',
    topic: 'everyday',
    answers: [
      { text: 'Keys', points: 34 },
      { text: 'Phone', points: 23 },
      { text: 'Wallet', points: 17 },
      { text: 'Glasses', points: 13 },
      { text: 'TV remote', points: 8 },
      { text: 'Socks', points: 5 },
    ],
  },

  // ---- general ----
  {
    text: 'Name something people are afraid of.',
    topic: 'general',
    answers: [
      { text: 'Spiders', points: 27 },
      { text: 'Heights', points: 23 },
      { text: 'Snakes', points: 17 },
      { text: 'The dark', points: 13 },
      { text: 'Death', points: 11 },
      { text: 'Clowns', points: 9 },
    ],
  },
  {
    text: 'Name something that makes a loud noise.',
    topic: 'general',
    answers: [
      { text: 'Thunder', points: 26 },
      { text: 'Fireworks', points: 21 },
      { text: 'A siren', points: 18 },
      { text: 'A dog barking', points: 14 },
      { text: 'A baby crying', points: 12 },
      { text: 'A jet engine', points: 9 },
    ],
  },

  // ---- food ----
  {
    text: 'Name a food people eat at the movies.',
    topic: 'food',
    answers: [
      { text: 'Popcorn', points: 42 },
      { text: 'Candy', points: 21 },
      { text: 'Nachos', points: 15 },
      { text: 'Hot dog', points: 11 },
      { text: 'Soda', points: 7 },
      { text: 'Pretzel', points: 4 },
    ],
  },
  {
    text: 'Name a topping people put on pizza.',
    topic: 'food',
    answers: [
      { text: 'Pepperoni', points: 35 },
      { text: 'Cheese', points: 22 },
      { text: 'Mushrooms', points: 15 },
      { text: 'Sausage', points: 12 },
      { text: 'Onions', points: 9 },
      { text: 'Peppers', points: 7 },
    ],
  },

  // ---- animals ----
  {
    text: 'Name an animal you might see at the zoo.',
    topic: 'animals',
    answers: [
      { text: 'Lion', points: 25 },
      { text: 'Elephant', points: 21 },
      { text: 'Monkey', points: 18 },
      { text: 'Giraffe', points: 15 },
      { text: 'Tiger', points: 12 },
      { text: 'Zebra', points: 9 },
    ],
  },
  {
    text: 'Name an animal that is hard to keep as a pet.',
    topic: 'animals',
    answers: [
      { text: 'Lion / tiger', points: 28 },
      { text: 'Snake', points: 20 },
      { text: 'Elephant', points: 16 },
      { text: 'Bear', points: 14 },
      { text: 'Alligator', points: 12 },
      { text: 'Shark', points: 10 },
    ],
  },

  // ---- home ----
  {
    text: 'Name something you might find in a junk drawer.',
    topic: 'home',
    answers: [
      { text: 'Batteries', points: 26 },
      { text: 'Pens', points: 22 },
      { text: 'Rubber bands', points: 16 },
      { text: 'Tape', points: 13 },
      { text: 'Scissors', points: 12 },
      { text: 'Keys', points: 6 },
      { text: 'Takeout menus', points: 5 },
    ],
  },
  {
    text: 'Name a chore people put off doing.',
    topic: 'home',
    answers: [
      { text: 'Dishes', points: 27 },
      { text: 'Laundry', points: 23 },
      { text: 'Vacuuming', points: 17 },
      { text: 'Taking out trash', points: 13 },
      { text: 'Cleaning bathroom', points: 11 },
      { text: 'Mowing the lawn', points: 9 },
    ],
  },

  // ---- travel ----
  {
    text: 'Name something you pack for a beach vacation.',
    topic: 'travel',
    answers: [
      { text: 'Sunscreen', points: 30 },
      { text: 'Swimsuit', points: 25 },
      { text: 'Towel', points: 18 },
      { text: 'Sunglasses', points: 12 },
      { text: 'Flip flops', points: 9 },
      { text: 'Hat', points: 6 },
    ],
  },

  // ---- entertainment ----
  {
    text: 'Name a board game families play together.',
    topic: 'entertainment',
    answers: [
      { text: 'Monopoly', points: 32 },
      { text: 'Scrabble', points: 19 },
      { text: 'Sorry', points: 15 },
      { text: 'Clue', points: 13 },
      { text: 'Candy Land', points: 11 },
      { text: 'Life', points: 10 },
    ],
  },
  {
    text: 'Name something people do to relax after work.',
    topic: 'everyday',
    answers: [
      { text: 'Watch TV', points: 30 },
      { text: 'Have a drink', points: 19 },
      { text: 'Take a nap', points: 16 },
      { text: 'Read', points: 13 },
      { text: 'Take a bath', points: 12 },
      { text: 'Exercise', points: 10 },
    ],
  },
  {
    text: 'Name a reason you might be late for work.',
    topic: 'everyday',
    answers: [
      { text: 'Traffic', points: 34 },
      { text: 'Slept in', points: 27 },
      { text: 'Bad weather', points: 14 },
      { text: 'Car trouble', points: 11 },
      { text: 'Kids', points: 8 },
      { text: 'Long line for coffee', points: 6 },
    ],
  },
  {
    text: 'Name something you bring to a picnic.',
    topic: 'food',
    answers: [
      { text: 'Sandwiches', points: 26 },
      { text: 'Drinks', points: 21 },
      { text: 'Chips', points: 17 },
      { text: 'Blanket', points: 14 },
      { text: 'Fruit', points: 12 },
      { text: 'Watermelon', points: 10 },
    ],
  },
  {
    text: 'Name a fruit that is yellow.',
    topic: 'food',
    answers: [
      { text: 'Banana', points: 40 },
      { text: 'Lemon', points: 24 },
      { text: 'Pineapple', points: 16 },
      { text: 'Mango', points: 11 },
      { text: 'Grapefruit', points: 9 },
    ],
  },
  {
    text: 'Name something people are addicted to.',
    topic: 'general',
    answers: [
      { text: 'Coffee', points: 28 },
      { text: 'Their phone', points: 24 },
      { text: 'Cigarettes', points: 16 },
      { text: 'Sugar', points: 12 },
      { text: 'Social media', points: 11 },
      { text: 'Shopping', points: 9 },
    ],
  },
  {
    text: 'Name something you do at the gym.',
    topic: 'general',
    answers: [
      { text: 'Lift weights', points: 31 },
      { text: 'Run / treadmill', points: 25 },
      { text: 'Stretch', points: 14 },
      { text: 'Swim', points: 11 },
      { text: 'Yoga', points: 10 },
      { text: 'Take a class', points: 9 },
    ],
  },
  {
    text: 'Name something you find on a beach.',
    topic: 'travel',
    answers: [
      { text: 'Sand', points: 29 },
      { text: 'Shells', points: 22 },
      { text: 'Water', points: 17 },
      { text: 'Umbrellas', points: 12 },
      { text: 'Seagulls', points: 11 },
      { text: 'Crabs', points: 9 },
    ],
  },
  {
    text: 'Name a holiday people decorate their house for.',
    topic: 'general',
    answers: [
      { text: 'Christmas', points: 45 },
      { text: 'Halloween', points: 28 },
      { text: 'Easter', points: 11 },
      { text: 'Thanksgiving', points: 9 },
      { text: 'Fourth of July', points: 7 },
    ],
  },
  {
    text: 'Name something a dog loves.',
    topic: 'animals',
    answers: [
      { text: 'Treats / bones', points: 30 },
      { text: 'Walks', points: 22 },
      { text: 'Belly rubs', points: 16 },
      { text: 'Toys', points: 13 },
      { text: 'Fetch', points: 11 },
      { text: 'Naps', points: 8 },
    ],
  },
  {
    text: 'Name something you keep in your car.',
    topic: 'home',
    answers: [
      { text: 'Sunglasses', points: 24 },
      { text: 'Phone charger', points: 21 },
      { text: 'Napkins', points: 16 },
      { text: 'Umbrella', points: 14 },
      { text: 'Spare change', points: 13 },
      { text: 'First aid kit', points: 7 },
    ],
  },
  {
    text: 'Name a word people shout when they get hurt.',
    topic: 'general',
    answers: [
      { text: 'Ouch', points: 38 },
      { text: 'Ow', points: 26 },
      { text: 'A swear word', points: 20 },
      { text: 'Help', points: 9 },
      { text: 'Oh no', points: 5 },
    ],
  },
];

// Full playable bank: curated questions first, then the large scraped set.
const SAMPLE_QUESTIONS = CURATED_QUESTIONS.concat(BANK_QUESTIONS);

// Distinct topics present in the bank (for host topic chips).
const TOPICS = [...new Set(SAMPLE_QUESTIONS.map((q) => q.topic))];

function hashQuestion(text) {
  return crypto.createHash('sha1').update(text.toLowerCase().trim()).digest('hex');
}

// Build a playable question object (attaches reveal flags + a stable hash).
function buildQuestion(raw) {
  return {
    text: raw.text,
    topic: raw.topic || 'general',
    hash: hashQuestion(raw.text),
    answers: raw.answers.map((a) => ({
      text: a.text,
      points: a.points,
      revealed: false,
    })),
  };
}

// A short, punchy "Name.../Tell me.../How many..." prompt — the kind that plays
// best in Fast Money (vs. a long survey-style question).
function isFmFriendly(q) {
  return q.text.length <= 70 &&
    /^(name|tell me|how many|a reason|what|which|when|where|give me|at what)/i.test(q.text);
}

// Curated Fast Money pool with stable hashes (for de-dupe).
const FM_BANK = FM_CURATED.map((raw) => ({ raw, hash: hashQuestion(raw.text) }));

// True for a Fast Money "opener" framing (the long first question — there's time
// to read it). The other four FM questions are 3-second sprints, so they stay short.
function isFmOpener(text) {
  return /^(we asked|on a scale|how many|what percentage|at what age)/i.test(text);
}

// Pick a random bank question (optionally by topic) not already used this game.
// opts.fmFriendly biases toward short Fast Money-style prompts.
// opts.fmOpener draws a curated classic-framing OPENER (first FM question only).
function getSampleQuestion(usedHashes = new Set(), topic = null, opts = {}) {
  // A question the host flagged as unplayable is out of the rotation for good —
  // treated exactly like one already used this game, in every pool below.
  const skip = (hash) => usedHashes.has(hash) || flagged.isFlagged(hash);

  if (opts.fmOpener) {
    let avail = FM_BANK.filter((e) => isFmOpener(e.raw.text) && !skip(e.hash));
    if (!avail.length) avail = FM_BANK.filter((e) => !skip(e.hash)); // any curated
    if (avail.length) return buildQuestion(avail[Math.floor(Math.random() * avail.length)].raw);
    opts = Object.assign({}, opts, { fmFriendly: true }); // exhausted → short bank Q
  }
  let pool = SAMPLE_QUESTIONS;
  if (topic && topic !== 'random') {
    const byTopic = SAMPLE_QUESTIONS.filter((q) => q.topic === topic);
    if (byTopic.length) pool = byTopic;
  }
  if (opts.fmFriendly) {
    const fm = pool.filter(isFmFriendly);
    if (fm.length) pool = fm;
  }
  // Sudden death wants an "obvious" question — a dominant #1 answer.
  if (opts.suddenDeath) {
    const obvious = pool.filter((q) => q.answers[0] && q.answers[0].points >= 40);
    if (obvious.length) pool = obvious;
  }
  let available = pool.filter((q) => !skip(hashQuestion(q.text)));
  // If this topic is exhausted, fall back to any unused question, then anything.
  if (!available.length) {
    available = SAMPLE_QUESTIONS.filter((q) => !skip(hashQuestion(q.text)));
  }
  // Last resort ignores "already used" but STILL honours flags — a flagged
  // question should never come back, even on an exhausted bank.
  if (!available.length) {
    available = SAMPLE_QUESTIONS.filter((q) => !flagged.isFlagged(hashQuestion(q.text)));
  }
  if (!available.length) available = SAMPLE_QUESTIONS;
  const raw = available[Math.floor(Math.random() * available.length)];
  return buildQuestion(raw);
}

module.exports = {
  SAMPLE_QUESTIONS,
  TOPICS,
  hashQuestion,
  buildQuestion,
  getSampleQuestion,
};
